name: mycountdowntimer # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: First app # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64

apps:
   mycountdowntimer:
     command: desktop-launch $SNAP/bin/mycountdowntimer
     #desktop: share/applications/MyCountDownTimer.desktop
     #plugs: [home, x11]
     plugs:
      - home
      - desktop
      - desktop-legacy
      - gsettings
      
parts:
   mycountdowntimer:
        after: [desktop-qt5]
        qt-version: qt5
        plugin:        qmake
        project-files: ["MyCountDownTimer.pro"]
        source:        .
        build-packages:
         - g++
        #
        override-build: |
          cp debian/scripts/retpoline-extract-one \
            $SNAPCRAFT_PART_BUILD/scripts/ubuntu-retpoline-extract-one
          snapcraftctl build
        stage-packages:
         - libc6
